SUPABASE_URL = "https://azkhsqsdwdfjnyuyfoud.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6a2hzcXNkd2Rmam55dXlmb3VkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NDc0ODAzOCwiZXhwIjoyMDgwMzI0MDM4fQ.Duuslhr8lg-brWCtLVhiCw2tjwuIGsqJUZzQcBGD2sc"
